# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: docker login -u $(dockerId) -p $(dockerPassword) $(azureDockerRegister)
  displayName: "ACR - Docker Login"
- script: docker build -t $(dockerId)/$(imageName) .
  displayName: "ACR - Docker Build $(imageName)"
- script: docker push $(azureDockerRegister)/$(imageName)
  displayName: "ACR - Docker push the built file."