version: '3'

services:
  main-web:
    image: testcore
    build:
      context: ./Testcore
      dockerfile: dockerfile
    ports:
      - "8080:80"
    container_name: testcore

    ####
    ##
    ## Ecosystem
    ##
    ####

  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "15672:15672"
    container_name: rabbitmq